### ISSUE TITLE
Add support for Structured Text fields

### ISSUE THREAD

**Issue by stefanoverna** [voorhoede/datocms-plugin-word-counter#1]
Great work guys!

It'd be great if you could also support structured text fields! You'd only need a function that converts ST nodes into a string. We've got [some documentation](https://www.datocms.com/docs/plugin-sdk/working-with-form-values#structured-text-fields), but here's the gist of it:

```ts
import { isText, Node } from 'datocms-structured-text-slate-utils';

function visit(
  tree: Node | Node[],
  callback: (node: Node, index: number, parents: Node[]) => void,
) {
  const all = (nodes: Node[], parents: Node[]) =>
    nodes.forEach((node, index) => one(node, index, parents));
  const one = (node: Node, index: number, parents: Node[]) => {
    if ('children' in node) {
      all(node.children, [node, ...parents]);
    }
    callback(node, index, parents);
  };
  if (Array.isArray(tree)) {
    all(tree, []);
  } else {
    one(tree, 0, []);
  }
}

export function structuredTextToString(value: Node[]): string {
  let result: string = '';

  visit(value, (node) => {
    if (!isText(node)) {
      return;
    }

    result += node.text;
  });

  return result;
}
```

So that in your `FieldAddon.tsx` you can do:

```ts
  const fieldValue: string =
    ctx.field.attributes.field_type === 'structured_text'
      ? structuredTextToString(get(ctx.formValues, ctx.fieldPath) as Node[])
      : String(get(ctx.formValues, ctx.fieldPath));
  const fieldStats: CountObject = counter(fieldValue);
```

**Comment by velomovies** [comment]
Hi @stefanoverna,
Thanks for the suggestion!

We actually wanted to add the structured text but didn't seem to get it working. We based the supported fields on the [`PluginAttributes`](https://github.com/datocms/plugins-sdk/blob/74ad64c5f6d99d23f3cb63903ba43dc1c434e7b2/packages/sdk/src/SiteApiSchema.ts#L3196) type where 'structured_text' isn't added in the `field_types` array. 

We have checked how to get it working by checking in the [Lorum ipsum plugin](https://github.com/datocms/plugins/blob/master/lorem-ipsum/src/index.tsx) and will add structured text support in the next version (v1.2.0).

**Comment by stefanoverna** [comment]
I see! But that `field_types` field is for legacy plugins!

Thanks, and let me know if you need any help from me!

**Comment by stefanoverna** [comment]
Uh, and `"previewImage": "docs/preview.gif"` in package.json can now also be an MP4 file. It will render better!

**Comment by velomovies** [comment]
When we used

```js
manualFieldExtensions() {
    return [
      {
        id: extensionId,
        name: 'Word counter',
        type: 'addon',
        fieldTypes: [
          'text',
          'string',
          'rich_text',
          'structured_text',
        ],
        configurable: true,
      },
    ]
}
 ```
We got an typescript error on the `manualFieldExtensions`: ` Type '"structured_text"' is not assignable to type '"string" | "boolean" | "date" | "date_time" | "float" | "integer" | "text" | "lat_lon" | "json" | "seo" | "link" | "links" | "video" | "color" | "slug" | "rich_text" | "file" | "gallery"'` which got us only working with those types.

We are now using the code below based on the Lorum ipsum plugin

```js
manualFieldExtensions() {
    return [
      {
        id: extensionId,
        name: 'Word counter',
        type: 'addon',
        fieldTypes: [
          'text',
          'string',
          'rich_text',
          'structured_text',
        ] as NonNullable<
          PluginAttributes['field_types']
        >,
        configurable: true,
      },
    ]
}
 ```

**Comment by stefanoverna** [comment]
You're right! SDK v0.3.33 fixes this!

**Comment by velomovies** [comment]
We have updated the plugin. From `v1.2.0` onwards you can use this plugin together with the structured text fields.

**Comment by stefanoverna** [comment]
Excellent, thanks so much! And we can wait to list you in our Partners page :) https://www.datocms.com/partners
