### ISSUE TITLE
Expose the word counter results in the API

### ISSUE THREAD

**Issue by JustinyAhin** [voorhoede/datocms-plugin-word-counter#5]
The plugin is very useful. I was wondering if its featured can be extended by exposing the word counter results to the DatoCMS content API. People would then be able to use these in sites frontend.

**Comment by andremendonca** [comment]
I am looking for this exactly, having the plugin at the editor is super nice, but we also display reading time to users on the front end

**Comment by velomovies** [comment]
Hi @JustinyAhin  and @andremendonca thanks for using the plugin and thanks for the suggestion!

We have implemented a way to expose all word count results in the API. When Dato had picked up version `1.3.0` of the plugin you can add a json field in the model where the word counter is implemented. If you add a JSON field with the id `[ID of the word counted field]_word_counter` it will be automatically hidden and save the results of the word count there.

Enjoy the plugin!

**Comment by ThinleyN** [comment]
@velomovies 

First of all, thanks a lot this awesome plugin. It is really really useful.

One problem I'm having with this is that I am not able to save the word count results in the JSON field. I used '[ID of word counted field]'_word_counter. The JSON field is hidden as expected. However, I am not able to see the results in the API.

<img width="920" alt="Screenshot 2022-06-23 at 17 46 49" src="https://user-images.githubusercontent.com/26631659/175352050-63712875-ad78-4c9d-8f2a-9b0df706fffc.png">

**Comment by velomovies** [comment]
Hi @ThinleyN,

Is the content localized? If so, the `content_word_counter` field should also be localized, otherwise there will be some unexpected behaviour.

If that's not the problem I need a bit more info, because I can't reproduce the problem. After installing the plugin it seems to work for me.

**Comment by ThinleyN** [comment]
Hi @velomovies 

I understood why it is happening. It seems like the plugin only starts saving the count to the JSON field after the value of the field is updated. So we cannot get the word count of contents that were already present before installing the plugin.

I already had the content in place before installing the plugin. I updated some values of the content and the plugin returned the word count in the API as expected.

**Comment by velomovies** [comment]
Thanks for explaining. That's a problem we have had for other plugins as well. The same sort of issue we had with the computed fields plugin (https://github.com/voorhoede/datocms-plugin-computed-fields/issues/14).

Unfortunately it seems there is no easier way than just opening models and updating everything manually. DatoCMS doesn't seem to have, at the moment, an easy way of getting all the data from one place and updating it with the new data for the word counter field.
